### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by threed-factory-store** [Brobin/usps-api#21]
pip install returns:

$ pip install usps-api
Defaulting to user installation because normal site-packages is not writeable
Collecting usps-api
  Downloading usps-api-0.5.tar.gz (5.0 kB)
  Preparing metadata (setup.py) ... done
Collecting lxml
  Downloading lxml-4.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 4.6 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from usps-api) (2.27.1)
Collecting xmltodict
  Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Building wheels for collected packages: usps-api
  Building wheel for usps-api (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/usps
      copying usps/__init__.py -> build/lib/usps
      copying usps/constants.py -> build/lib/usps
      copying usps/address.py -> build/lib/usps
      copying usps/tests.py -> build/lib/usps
      copying usps/usps.py -> build/lib/usps
      running egg_info
      writing usps_api.egg-info/PKG-INFO
      writing dependency_links to usps_api.egg-info/dependency_links.txt
      writing requirements to usps_api.egg-info/requires.txt
      writing top-level names to usps_api.egg-info/top_level.txt
      reading manifest file 'usps_api.egg-info/SOURCES.txt'
      writing manifest file 'usps_api.egg-info/SOURCES.txt'
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8ild4rhv/usps-api_5380f40a8df740baa9beb673c4d78c88/setup.py", line 7, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 335, in run
          self.run_command('install')
        File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/local/lib/python3.10/distutils/command/install.py", line 580, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/distutils/dist.py", line 984, in run_command
          cmd_obj.ensure_finalized()
        File "/usr/local/lib/python3.10/distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
          self.set_undefined_options('install',('install_layout','install_layout'))
        File "/usr/local/lib/python3.10/distutils/cmd.py", line 290, in set_undefined_options
          setattr(self, dst_option, getattr(src_cmd_obj, src_option))
        File "/usr/local/lib/python3.10/distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout. Did you mean: 'install_platlib'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for usps-api
  Running setup.py clean for usps-api
Failed to build usps-api
Installing collected packages: xmltodict, lxml, usps-api
  Running setup.py install for usps-api ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for usps-api did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/usps
      copying usps/__init__.py -> build/lib/usps
      copying usps/constants.py -> build/lib/usps
      copying usps/address.py -> build/lib/usps
      copying usps/tests.py -> build/lib/usps
      copying usps/usps.py -> build/lib/usps
      running egg_info
      writing usps_api.egg-info/PKG-INFO
      writing dependency_links to usps_api.egg-info/dependency_links.txt
      writing requirements to usps_api.egg-info/requires.txt
      writing top-level names to usps_api.egg-info/top_level.txt
      reading manifest file 'usps_api.egg-info/SOURCES.txt'
      writing manifest file 'usps_api.egg-info/SOURCES.txt'
      running install_lib
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8ild4rhv/usps-api_5380f40a8df740baa9beb673c4d78c88/setup.py", line 7, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/local/lib/python3.10/distutils/command/install.py", line 580, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/distutils/dist.py", line 984, in run_command
          cmd_obj.ensure_finalized()
        File "/usr/local/lib/python3.10/distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
          self.set_undefined_options('install',('install_layout','install_layout'))
        File "/usr/local/lib/python3.10/distutils/cmd.py", line 290, in set_undefined_options
          setattr(self, dst_option, getattr(src_cmd_obj, src_option))
        File "/usr/local/lib/python3.10/distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout. Did you mean: 'install_platlib'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> usps-api

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by threed-factory-store** [comment]
Never mind.  Looks like this is an issue with the version of pip & setuptools distributed with Ubuntu.
